### ISSUE TITLE
Ability to manage customers 

### ISSUE THREAD

**Issue by ryanmwilliams** [Dwolla/dwolla.net#5]
There is currently no support in the SDK for managing customers (creating, finding, updating). Adding these capabilities will improve the white label experience.

Doc: https://docsv2.dwolla.com/#customers

**Comment by lochnesh** [comment]
The dwolla.net SDK is used solely for API v1, therefore it doesn't contain support to create white label customers as this functionality exists only in our v2 API.  We do not have a supported .NET client library for API v2 at this time.  However, based on feedback and demand, it is something that we will consider creating in the future.

**Comment by 501st-alpha1** [comment]
My company has an ASP.NET project that we are going to add Dwolla to (and we want to use the v2 API), so I'm interested in helping out with this. Should I send PRs to this project, or would you prefer to have a separate package created?

**Comment by spencerhunter** [comment]
@501st-alpha1 Since a lot has changed from an API design perspective from v1 to v2, I'd recommend creating a new wrapper for the v2 API. Unfortunately it's not on our short term roadmap to rewrite a new C#/NET wrapper for our v2 API, so if you're interested in writing one then that'd be awesome! There are likely developers in the Dwolla developer community that would take advantage of it as well.

**Comment by 501st-alpha1** [comment]
Sounds good! I created a new repo: [dwolla.net-v2](https://github.com/501st-alpha1/dwolla.net-v2). I'll be basing it off this library as a starting point, but I'll eventually remove any v1 code and will only support v2.
